/* Automatically generated by './build/entry.js' */
import VNodeRender from '../packages/v-node-render/index.js'

const components = [
  VNodeRender,
]

const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export {
  // components
  VNodeRender,
}

export default {
  install,
  VNodeRender
}
